// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TimeTest.proto

package grpc.abc;

public interface MyRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.util.MyRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string datasend = 1;</code>
   * @return The datasend.
   */
  String getDatasend();
  /**
   * <code>string datasend = 1;</code>
   * @return The bytes for datasend.
   */
  com.google.protobuf.ByteString
      getDatasendBytes();
}
