// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TimeTest.proto

package grpc.abc;

public interface MyResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:grpc.util.MyResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string dataget = 1;</code>
   * @return The dataget.
   */
  String getDataget();
  /**
   * <code>string dataget = 1;</code>
   * @return The bytes for dataget.
   */
  com.google.protobuf.ByteString
      getDatagetBytes();
}
