// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: TimeTest.proto

package grpc.abc;

public final class TimeTestProto {
  private TimeTestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_MyRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_MyRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_grpc_MyResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_grpc_MyResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016TimeTest.proto\022\004grpc\"\035\n\tMyRequest\022\020\n\010d" +
      "atasend\030\001 \001(\t\"\035\n\nMyResponse\022\017\n\007dataget\030\001" +
      " \001(\t2I\n\tTimeCount\022<\n\025GetMessageByMyMessa" +
      "ge\022\017.grpc.util.MyRequest\032\020.grpc.util.MyResponse\"\000B" +
      "\027\n\004grpcB\rTimeTestProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_grpc_MyRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_grpc_MyRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_MyRequest_descriptor,
        new String[] { "Datasend", });
    internal_static_grpc_MyResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_grpc_MyResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_grpc_MyResponse_descriptor,
        new String[] { "Dataget", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
